import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { chromium } from 'playwright';

const BASE_URL = process.env.SMOKE_BASE_URL || 'http://127.0.0.1:8788';
const REPORT_PATH = path.resolve('audit/smoke/browser-smoke-report.md');

const results = [];

async function runStep(name, fn) {
  const startedAt = Date.now();
  try {
    const detail = await fn();
    results.push({
      name,
      status: 'pass',
      durationMs: Date.now() - startedAt,
      detail: detail || '',
    });
  } catch (error) {
    results.push({
      name,
      status: 'fail',
      durationMs: Date.now() - startedAt,
      detail: error?.message || String(error),
    });
  }
}

async function closeSettingsIfOpen(page) {
  const panel = page.locator('#settings-panel');
  const panelClass = await panel.getAttribute('class');
  if (panelClass && panelClass.includes('open')) {
    await page.click('#close-settings');
    await page.waitForTimeout(120);
  }
  await page.evaluate(() => {
    document.getElementById('settings-panel')?.classList.remove('open');
    document.getElementById('settings-overlay')?.classList.remove('open');
  });
}

function getSummary() {
  const passCount = results.filter((item) => item.status === 'pass').length;
  const failCount = results.length - passCount;
  return { passCount, failCount };
}

function buildReport() {
  const { passCount, failCount } = getSummary();
  const lines = [
    '# Browser Smoke Report',
    '',
    `- Base URL: ${BASE_URL}`,
    `- Timestamp: ${new Date().toISOString()}`,
    `- Result: ${failCount === 0 ? 'PASS' : 'FAIL'}`,
    `- Passed: ${passCount}/${results.length}`,
    '',
    '| Step | Status | Duration(ms) | Detail |',
    '|---|---|---:|---|',
    ...results.map((item) => {
      const status = item.status === 'pass' ? 'PASS' : 'FAIL';
      const detail = String(item.detail || '').replace(/\|/g, '\\|');
      return `| ${item.name} | ${status} | ${item.durationMs} | ${detail} |`;
    }),
    '',
    '## Notes',
    '- This report is generated by Playwright automation against local Pages dev server.',
    '- Includes desktop and mobile viewport smoke scenarios.',
  ];
  return lines.join('\n');
}

async function getCanvasGeometry(page, id) {
  return page.evaluate(async (elemId) => {
    const { getCanvasData } = await import('/js/canvas.js');
    const target = getCanvasData().elements.find((e) => e.id === elemId);
    if (!target) return null;
    return { x: target.x, y: target.y, w: target.w, h: target.h };
  }, id);
}

async function main() {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();

  await runStep('Load app shell', async () => {
    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await page.waitForSelector('#prompt-input', { timeout: 10000 });
    return 'main UI loaded';
  });

  await runStep('Managed mode has no model input', async () => {
    await page.click('#btn-settings');
    await page.waitForSelector('#settings-panel.open', { timeout: 5000 });
    const count = await page.locator('#managed-model-name').count();
    if (count !== 0) {
      throw new Error('managed mode still exposes model input');
    }
    await closeSettingsIfOpen(page);
    return 'managed panel hidden model input confirmed';
  });

  await runStep('Managed mode request omits model field', async () => {
    let capturedBody = null;
    const onRequest = (request) => {
      if (request.url().endsWith('/api/chat') && request.method() === 'POST') {
        try {
          capturedBody = request.postDataJSON();
        } catch {
          capturedBody = null;
        }
      }
    };

    page.on('request', onRequest);
    await page.click('#btn-settings');
    await page.check('input[name="api-mode"][value="managed"]');
    await page.click('#test-connection');
    await page.waitForTimeout(1200);
    await closeSettingsIfOpen(page);
    page.off('request', onRequest);

    if (!capturedBody || !Array.isArray(capturedBody.messages)) {
      throw new Error('failed to capture /api/chat request body');
    }
    if (Object.prototype.hasOwnProperty.call(capturedBody, 'model')) {
      throw new Error('managed request should not send model');
    }
    return 'captured /api/chat body without model';
  });

  await runStep('Scene UI uses 光源1~4 and includes 光源4 controls', async () => {
    await page.evaluate(async () => {
      const { initScene } = await import('/js/scene.js');
      const section = document.getElementById('scene-section');
      section.style.display = '';
      initScene('scene-container');
    });

    const light4Card = await page.locator('#scene-container .light-card-hair').count();
    const legendText = await page.locator('#scene-container .scene-legend-items').innerText();
    if (light4Card === 0) throw new Error('missing light4 card');
    if (!legendText.includes('光源1') || !legendText.includes('光源4')) {
      throw new Error(`unexpected legend: ${legendText}`);
    }
    return 'legend and light cards include 光源1~4';
  });

  await runStep('Three-view synchronized drag works for camera and light4', async () => {
    const topCamera = page.locator('#scene-container .scene-view[data-view="top"] .scene-camera[data-id="camera"]');
    const frontCamera = page.locator('#scene-container .scene-view[data-view="front"] .scene-camera[data-id="camera"]');
    const sideCamera = page.locator('#scene-container .scene-view[data-view="side"] .scene-camera[data-id="camera"]');

    const box = await topCamera.boundingBox();
    if (!box) throw new Error('unable to resolve top camera');
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width * 0.75, box.y + box.height * 0.75);
    await page.mouse.up();

    const camSynced = await page.evaluate(() => {
      const getPct = (el, key) => Number((el?.style?.[key] || '0').replace('%', ''));
      const top = document.querySelector('#scene-container .scene-view[data-view="top"] .scene-camera[data-id="camera"]');
      const front = document.querySelector('#scene-container .scene-view[data-view="front"] .scene-camera[data-id="camera"]');
      const side = document.querySelector('#scene-container .scene-view[data-view="side"] .scene-camera[data-id="camera"]');
      const topX = getPct(top, 'left');
      const topY = getPct(top, 'top');
      const frontX = getPct(front, 'left');
      const frontY = getPct(front, 'top');
      const sideX = getPct(side, 'left');
      const sideY = getPct(side, 'top');
      return {
        ok: Math.abs(topX - frontX) < 0.6 && Math.abs(topY - sideX) < 0.6,
        topX, topY, frontX, frontY, sideX, sideY,
      };
    });
    if (!camSynced.ok) {
      throw new Error(`camera not synced: ${JSON.stringify(camSynced)}`);
    }

    const sideLight4 = page.locator('#scene-container .scene-view[data-view="side"] .scene-light[data-id="light-hair"]');
    const sideBox = await sideLight4.boundingBox();
    if (!sideBox) throw new Error('unable to resolve side light4');
    await page.mouse.move(sideBox.x + sideBox.width / 2, sideBox.y + sideBox.height / 2);
    await page.mouse.down();
    await page.mouse.move(sideBox.x + sideBox.width * 0.85, sideBox.y + sideBox.height * 0.6);
    await page.mouse.up();

    const lightSynced = await page.evaluate(() => {
      const getPct = (el, key) => Number((el?.style?.[key] || '0').replace('%', ''));
      const top = document.querySelector('#scene-container .scene-view[data-view="top"] .scene-light[data-id="light-hair"]');
      const front = document.querySelector('#scene-container .scene-view[data-view="front"] .scene-light[data-id="light-hair"]');
      const side = document.querySelector('#scene-container .scene-view[data-view="side"] .scene-light[data-id="light-hair"]');
      const topY = getPct(top, 'top');
      const frontY = getPct(front, 'top');
      const sideY = getPct(side, 'top');
      return {
        ok: Math.abs(frontY - sideY) < 0.6,
        topY, frontY, sideY,
      };
    });
    if (!lightSynced.ok) {
      throw new Error(`light4 not synced: ${JSON.stringify(lightSynced)}`);
    }

    const frontExists = await frontCamera.count();
    const sideExists = await sideCamera.count();
    return `cameraSynced=${camSynced.ok}, light4Synced=${lightSynced.ok}, front=${frontExists}, side=${sideExists}`;
  });

  await runStep('Coverage masks exist and respond to light type/lumens changes', async () => {
    const topCoverageSelector = '#scene-container .scene-view[data-view="top"] .scene-coverage[data-entity="light-key"]';
    await page.waitForSelector(topCoverageSelector, { timeout: 5000 });

    const before = await page.$eval(topCoverageSelector, (el) => ({
      width: el.style.width,
      clip: el.style.clipPath,
    }));

    await page.selectOption('#scene-container .light-card-key .light-type-select', '霓虹灯');
    await page.fill('#scene-container .light-card-key .light-lm-input', '9000');
    await page.keyboard.press('Enter');
    await page.waitForTimeout(200);

    const after = await page.$eval(topCoverageSelector, (el) => ({
      width: el.style.width,
      clip: el.style.clipPath,
    }));

    if (!after.width || before.width === after.width) {
      throw new Error(`coverage width did not change: before=${before.width}, after=${after.width}`);
    }
    if (!after.clip || before.clip === after.clip) {
      throw new Error(`coverage clip did not change: before=${before.clip}, after=${after.clip}`);
    }
    return `coverage changed ${before.width} -> ${after.width}`;
  });

  await runStep('Canvas supports resize handle', async () => {
    await page.evaluate(async () => {
      const { initCanvas } = await import('/js/canvas.js');
      const section = document.getElementById('canvas-section');
      section.style.display = '';
      initCanvas('canvas-board', 'layer-panel', [
        { id: 'elem_resize', type: 'character', layer: 'foreground', name: '可缩放对象', x: 50, y: 50, w: 18, h: 28, zIndex: 1 },
      ]);
    });

    await page.click('#layer-panel .layer-tag[data-id="elem_resize"]');
    const handle = page.locator('#canvas-board .elem-box[data-id="elem_resize"] .elem-resize-handle');
    const hb = await handle.boundingBox();
    if (!hb) throw new Error('resize handle not found');

    const before = await getCanvasGeometry(page, 'elem_resize');
    await page.mouse.move(hb.x + hb.width / 2, hb.y + hb.height / 2);
    await page.mouse.down();
    await page.mouse.move(hb.x + hb.width / 2 + 28, hb.y + hb.height / 2 + 22);
    await page.mouse.up();
    const after = await getCanvasGeometry(page, 'elem_resize');
    if (!before || !after || after.w <= before.w || after.h <= before.h) {
      throw new Error(`resize failed: before=${JSON.stringify(before)} after=${JSON.stringify(after)}`);
    }
    return `size ${before.w}x${before.h} -> ${after.w}x${after.h}`;
  });

  await runStep('Alt+click layer tag enters focus mode and cancel rolls back', async () => {
    await page.evaluate(async () => {
      const { initCanvas } = await import('/js/canvas.js');
      initCanvas('canvas-board', 'layer-panel', [
        { id: 'elem_focus', type: 'character', layer: 'foreground', name: '焦点对象', x: 45, y: 45, w: 18, h: 24, zIndex: 1 },
        { id: 'elem_other', type: 'object', layer: 'background', name: '背景对象', x: 58, y: 56, w: 28, h: 20, zIndex: 0 },
      ]);
    });

    const before = await getCanvasGeometry(page, 'elem_focus');
    await page.click('#layer-panel .layer-tag[data-id="elem_focus"]', { modifiers: ['Alt'] });
    await page.waitForSelector('#layer-panel .layer-focus-actions', { timeout: 3000 });

    const focusBox = await page.locator('#canvas-board .elem-box[data-id="elem_focus"] .elem-resize-handle').boundingBox();
    if (!focusBox) throw new Error('focus resize handle not found');
    await page.mouse.move(focusBox.x + focusBox.width / 2, focusBox.y + focusBox.height / 2);
    await page.mouse.down();
    await page.mouse.move(focusBox.x + focusBox.width / 2 + 18, focusBox.y + focusBox.height / 2 + 18);
    await page.mouse.up();

    await page.click('#layer-panel .layer-focus-cancel');
    const after = await getCanvasGeometry(page, 'elem_focus');

    const diff = Math.abs((after?.w || 0) - (before?.w || 0)) + Math.abs((after?.h || 0) - (before?.h || 0));
    if (!before || !after || diff > 0.6) {
      throw new Error(`focus cancel rollback failed: before=${JSON.stringify(before)} after=${JSON.stringify(after)}`);
    }
    return 'cancel rollback ok';
  });

  await runStep('Alt+click focus mode complete persists changes', async () => {
    const before = await getCanvasGeometry(page, 'elem_focus');
    await page.click('#layer-panel .layer-tag[data-id="elem_focus"]', { modifiers: ['Alt'] });
    await page.waitForSelector('#layer-panel .layer-focus-actions', { timeout: 3000 });

    const box = await page.locator('#canvas-board .elem-box[data-id="elem_focus"]').boundingBox();
    if (!box) throw new Error('focus box missing');
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + 20, box.y + box.height / 2 - 10);
    await page.mouse.up();

    await page.click('#layer-panel .layer-focus-apply');
    const after = await getCanvasGeometry(page, 'elem_focus');

    if (!before || !after) throw new Error('missing geometry');
    const moved = Math.abs(after.x - before.x) + Math.abs(after.y - before.y);
    if (moved < 0.8) {
      throw new Error(`focus apply did not persist move: before=${JSON.stringify(before)} after=${JSON.stringify(after)}`);
    }
    return `position ${before.x},${before.y} -> ${after.x},${after.y}`;
  });

  await runStep('Ctrl+click overlap selection cycles target', async () => {
    await page.evaluate(async () => {
      const { initCanvas } = await import('/js/canvas.js');
      initCanvas('canvas-board', 'layer-panel', [
        { id: 'elem_back', type: 'object', layer: 'background', name: '后景A', x: 50, y: 50, w: 28, h: 22, zIndex: 0 },
        { id: 'elem_front', type: 'character', layer: 'foreground', name: '前景B', x: 50, y: 50, w: 24, h: 30, zIndex: 1 },
      ]);
    });

    const target = page.locator('#canvas-board .elem-box[data-id="elem_front"]');
    const box = await target.boundingBox();
    if (!box) throw new Error('unable to resolve overlapped element box');

    await page.click('#layer-panel .layer-tag[data-id="elem_front"]');
    const firstSelected = await page.locator('#canvas-board .elem-box.selected').getAttribute('data-id');
    await target.click({
      modifiers: ['Control'],
      position: { x: Math.max(2, Math.floor(box.width / 2)), y: Math.max(2, Math.floor(box.height / 2)) },
    });
    const secondSelected = await page.locator('#canvas-board .elem-box.selected').getAttribute('data-id');

    if (!firstSelected || !secondSelected || firstSelected === secondSelected) {
      throw new Error(`selection did not cycle: first=${firstSelected}, second=${secondSelected}`);
    }
    return `cycled ${firstSelected} -> ${secondSelected}`;
  });

  await runStep('Mobile portrait scene fold sections are visible and interactive', async () => {
    const mobileContext = await browser.newContext({
      viewport: { width: 390, height: 844 },
      userAgent:
        'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
      isMobile: true,
      hasTouch: true,
    });
    const mobilePage = await mobileContext.newPage();

    await mobilePage.goto(BASE_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await mobilePage.evaluate(async () => {
      const { initScene } = await import('/js/scene.js');
      const section = document.getElementById('scene-section');
      section.style.display = '';
      initScene('scene-container');
    });

    await mobilePage.waitForSelector('#scene-container .scene-fold-summary', { timeout: 5000 });
    const foldCount = await mobilePage.locator('#scene-container .scene-fold').count();
    if (foldCount < 4) throw new Error(`expected >=4 fold sections, got ${foldCount}`);

    const viewOpen = await mobilePage.locator('#scene-container .scene-fold-views').evaluate((el) => el.open);
    if (!viewOpen) throw new Error('views fold should be open by default on mobile');

    await mobilePage.click('#scene-container .scene-fold-lights > .scene-fold-summary');
    await mobilePage.waitForTimeout(120);
    const lightsOpen = await mobilePage.locator('#scene-container .scene-fold-lights').evaluate((el) => el.open);
    if (!lightsOpen) throw new Error('lights fold did not open after click');

    await mobileContext.close();
    return `folds=${foldCount}, viewsOpen=${viewOpen}, lightsOpen=${lightsOpen}`;
  });

  await context.close();
  await browser.close();

  const report = buildReport();
  await fs.mkdir(path.dirname(REPORT_PATH), { recursive: true });
  await fs.writeFile(REPORT_PATH, report, 'utf8');
  console.log(`Smoke report written: ${REPORT_PATH}`);
}

main().catch(async (error) => {
  await fs.mkdir(path.dirname(REPORT_PATH), { recursive: true });
  const fallback = [
    '# Browser Smoke Report',
    '',
    '- Result: FAIL',
    `- Fatal error: ${error?.stack || error?.message || String(error)}`,
  ].join('\n');
  await fs.writeFile(REPORT_PATH, fallback, 'utf8');
  console.error(error);
  process.exitCode = 1;
});

