import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { chromium } from 'playwright';

const BASE_URL = process.env.SMOKE_BASE_URL || 'http://127.0.0.1:8788';
const REPORT_PATH = path.resolve('audit/smoke/browser-smoke-report.md');

const results = [];

async function runStep(name, fn) {
  const startedAt = Date.now();
  try {
    const detail = await fn();
    results.push({
      name,
      status: 'pass',
      durationMs: Date.now() - startedAt,
      detail: detail || '',
    });
  } catch (error) {
    results.push({
      name,
      status: 'fail',
      durationMs: Date.now() - startedAt,
      detail: error?.message || String(error),
    });
  }
}

async function closeSettingsIfOpen(page) {
  const panel = page.locator('#settings-panel');
  const panelClass = await panel.getAttribute('class');
  if (panelClass && panelClass.includes('open')) {
    await page.click('#close-settings');
    await page.waitForTimeout(120);
  }
  await page.evaluate(() => {
    document.getElementById('settings-panel')?.classList.remove('open');
    document.getElementById('settings-overlay')?.classList.remove('open');
  });
}

function getSummary() {
  const passCount = results.filter((item) => item.status === 'pass').length;
  const failCount = results.length - passCount;
  return { passCount, failCount };
}

function buildReport() {
  const { passCount, failCount } = getSummary();
  const lines = [
    '# Browser Smoke Report',
    '',
    `- Base URL: ${BASE_URL}`,
    `- Timestamp: ${new Date().toISOString()}`,
    `- Result: ${failCount === 0 ? 'PASS' : 'FAIL'}`,
    `- Passed: ${passCount}/${results.length}`,
    '',
    '| Step | Status | Duration(ms) | Detail |',
    '|---|---|---:|---|',
    ...results.map((item) => {
      const status = item.status === 'pass' ? 'PASS' : 'FAIL';
      const detail = String(item.detail || '').replace(/\|/g, '\\|');
      return `| ${item.name} | ${status} | ${item.durationMs} | ${detail} |`;
    }),
    '',
    '## Notes',
    '- This report is generated by Playwright automation against local Pages dev server.',
    '- Canvas smoke uses seeded overlapping elements to verify Alt+click overlap selection and direct layer edit.',
  ];
  return lines.join('\n');
}

async function main() {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();

  await runStep('Load app shell', async () => {
    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await page.waitForSelector('#prompt-input', { timeout: 10000 });
    return 'main UI loaded';
  });

  await runStep('Managed mode has no model input', async () => {
    await page.click('#btn-settings');
    await page.waitForSelector('#settings-panel.open', { timeout: 5000 });
    const count = await page.locator('#managed-model-name').count();
    if (count !== 0) {
      throw new Error('managed mode still exposes model input');
    }
    await closeSettingsIfOpen(page);
    return 'managed panel hidden model input confirmed';
  });

  await runStep('Custom mode blocks missing required fields', async () => {
    await page.click('#btn-settings');
    await page.check('input[name="api-mode"][value="custom"]');
    await closeSettingsIfOpen(page);
    await page.fill('#prompt-input', '雨夜街头霓虹，人物半身像');
    await page.waitForTimeout(800);
    await page.evaluate(() => {
      document.querySelectorAll('#toast-container .toast').forEach((node) => node.remove());
    });
    await page.click('#btn-analyze');
    await page.waitForTimeout(500);
    const toastText = await page.locator('#toast-container .toast').last().innerText();
    if (!toastText.includes('自定义模式缺少必填项')) {
      throw new Error(`unexpected toast: ${toastText}`);
    }
    return toastText;
  });

  await runStep('Managed mode request omits model field', async () => {
    let capturedBody = null;
    const onRequest = (request) => {
      if (request.url().endsWith('/api/chat') && request.method() === 'POST') {
        try {
          capturedBody = request.postDataJSON();
        } catch {
          capturedBody = null;
        }
      }
    };

    page.on('request', onRequest);
    await page.click('#btn-settings');
    await page.check('input[name="api-mode"][value="managed"]');
    await page.click('#test-connection');
    await page.waitForTimeout(1200);
    await closeSettingsIfOpen(page);
    page.off('request', onRequest);

    if (!capturedBody || !Array.isArray(capturedBody.messages)) {
      throw new Error('failed to capture /api/chat request body');
    }
    if (Object.prototype.hasOwnProperty.call(capturedBody, 'model')) {
      throw new Error('managed request should not send model');
    }
    return 'captured /api/chat body without model';
  });

  await runStep('Canvas Alt+click overlap selection cycles target', async () => {
    await closeSettingsIfOpen(page);
    await page.evaluate(async () => {
      const { initCanvas } = await import('/js/canvas.js');
      const section = document.getElementById('canvas-section');
      section.style.display = '';
      initCanvas('canvas-board', 'layer-panel', [
        { id: 'elem_back', type: 'object', layer: 'background', name: '后景A', x: 50, y: 50, w: 28, h: 22, zIndex: 0 },
        { id: 'elem_front', type: 'character', layer: 'foreground', name: '前景B', x: 50, y: 50, w: 24, h: 30, zIndex: 1 },
      ]);
    });

    const target = page.locator('#canvas-board .elem-box[data-id="elem_front"]');
    const box = await target.boundingBox();
    if (!box) throw new Error('unable to resolve overlapped element box');
    const x = Math.round(box.x + box.width / 2);
    const y = Math.round(box.y + box.height / 2);

    await page.click('#layer-panel .layer-tag[data-id="elem_front"]');
    const firstSelected = await page.locator('#canvas-board .elem-box.selected').getAttribute('data-id');
    if (!firstSelected) {
      throw new Error('unable to select initial top element');
    }
    await target.click({
      modifiers: ['Alt'],
      position: { x: Math.max(2, Math.floor(box.width / 2)), y: Math.max(2, Math.floor(box.height / 2)) },
    });
    const secondSelected = await page.locator('#canvas-board .elem-box.selected').getAttribute('data-id');

    if (!firstSelected || !secondSelected || firstSelected === secondSelected) {
      throw new Error(`selection did not cycle: first=${firstSelected}, second=${secondSelected}`);
    }
    return `cycled ${firstSelected} -> ${secondSelected}`;
  });

  await runStep('Layer panel direct edit opens popup', async () => {
    await closeSettingsIfOpen(page);
    await page.click('#layer-panel .layer-tag .layer-tag-edit');
    await page.waitForSelector('.edit-popup', { timeout: 3000 });
    return 'edit popup opened from layer panel';
  });

  await runStep('Dark mode text readability plate active', async () => {
    await page.evaluate(() => {
      document.documentElement.setAttribute('data-theme', 'dark');
    });

    const styleInfo = await page.evaluate(() => {
      const nameEl = document.querySelector('#canvas-board .elem-box-name');
      if (!nameEl) return null;
      const style = window.getComputedStyle(nameEl);
      return {
        backgroundColor: style.backgroundColor,
        color: style.color,
        textShadow: style.textShadow,
      };
    });

    if (!styleInfo) {
      throw new Error('no canvas name label found');
    }
    if (!styleInfo.backgroundColor || styleInfo.backgroundColor === 'rgba(0, 0, 0, 0)') {
      throw new Error(`label plate not applied: ${JSON.stringify(styleInfo)}`);
    }
    if (!styleInfo.textShadow || styleInfo.textShadow === 'none') {
      throw new Error(`text shadow not applied: ${JSON.stringify(styleInfo)}`);
    }
    return JSON.stringify(styleInfo);
  });

  await runStep('Scene view shows axis ticks and coordinate readout', async () => {
    await page.evaluate(async () => {
      const { initScene } = await import('/js/scene.js');
      const section = document.getElementById('scene-section');
      section.style.display = '';
      initScene('scene-container');
    });

    await page.waitForSelector('#scene-container .scene-axis-x span', { timeout: 5000 });
    const xTicks = await page.locator('#scene-container .scene-axis-x span').count();
    const yTicks = await page.locator('#scene-container .scene-axis-y span').count();
    const readoutCount = await page.locator('#scene-coord-readout span').count();

    if (xTicks < 5 || yTicks < 5 || readoutCount < 2) {
      throw new Error(`axis/readout missing: xTicks=${xTicks}, yTicks=${yTicks}, readout=${readoutCount}`);
    }
    return `xTicks=${xTicks}, yTicks=${yTicks}, readout=${readoutCount}`;
  });

  await context.close();
  await browser.close();

  const report = buildReport();
  await fs.mkdir(path.dirname(REPORT_PATH), { recursive: true });
  await fs.writeFile(REPORT_PATH, report, 'utf8');
  console.log(`Smoke report written: ${REPORT_PATH}`);
}

main().catch(async (error) => {
  await fs.mkdir(path.dirname(REPORT_PATH), { recursive: true });
  const fallback = [
    '# Browser Smoke Report',
    '',
    '- Result: FAIL',
    `- Fatal error: ${error?.stack || error?.message || String(error)}`,
  ].join('\n');
  await fs.writeFile(REPORT_PATH, fallback, 'utf8');
  console.error(error);
  process.exitCode = 1;
});
